[package]
name = "test_build"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bumpalo = "3.16.0"
libR-sys = "0.6.0"

[dev-dependencies]
insta = { version = "1.36.1", features = ["yaml"] }
